package com.cyuu.dao;

import com.cyuu.dataObject.CADao;
import org.springframework.stereotype.Repository;

@Repository
public interface CADaoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table from_ca
     *
     * @mbg.generated Thu Nov 24 17:41:58 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table from_ca
     *
     * @mbg.generated Thu Nov 24 17:41:58 CST 2022
     * @return
     */
    int insert(CADao row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table from_ca
     *
     * @mbg.generated Thu Nov 24 17:41:58 CST 2022
     */
    int insertSelective(CADao row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table from_ca
     *
     * @mbg.generated Thu Nov 24 17:41:58 CST 2022
     */
    CADao selectInfo();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table from_ca
     *
     * @mbg.generated Thu Nov 24 17:41:58 CST 2022
     */
    int updateByPrimaryKeySelective(CADao row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table from_ca
     *
     * @mbg.generated Thu Nov 24 17:41:58 CST 2022
     */
    int updateByPrimaryKeyWithBLOBs(CADao row);
}