package com.cyuu.dataObject;

import lombok.Data;

@Data
public class CADao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column from_ca.id
     *
     * @mbg.generated Thu Nov 24 17:41:58 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column from_ca.cipher1
     *
     * @mbg.generated Thu Nov 24 17:41:58 CST 2022
     */
    private String cipher1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column from_ca.cipher2
     *
     * @mbg.generated Thu Nov 24 17:41:58 CST 2022
     */
    private String cipher2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column from_ca.pk
     *
     * @mbg.generated Thu Nov 24 17:41:58 CST 2022
     */
    private String pk;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column from_ca.id
     *
     * @return the value of from_ca.id
     *
     * @mbg.generated Thu Nov 24 17:41:58 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column from_ca.id
     *
     * @param id the value for from_ca.id
     *
     * @mbg.generated Thu Nov 24 17:41:58 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column from_ca.cipher1
     *
     * @return the value of from_ca.cipher1
     *
     * @mbg.generated Thu Nov 24 17:41:58 CST 2022
     */
    public String getCipher1() {
        return cipher1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column from_ca.cipher1
     *
     * @param cipher1 the value for from_ca.cipher1
     *
     * @mbg.generated Thu Nov 24 17:41:58 CST 2022
     */
    public void setCipher1(String cipher1) {
        this.cipher1 = cipher1 == null ? null : cipher1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column from_ca.cipher2
     *
     * @return the value of from_ca.cipher2
     *
     * @mbg.generated Thu Nov 24 17:41:58 CST 2022
     */
    public String getCipher2() {
        return cipher2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column from_ca.cipher2
     *
     * @param cipher2 the value for from_ca.cipher2
     *
     * @mbg.generated Thu Nov 24 17:41:58 CST 2022
     */
    public void setCipher2(String cipher2) {
        this.cipher2 = cipher2 == null ? null : cipher2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column from_ca.pk
     *
     * @return the value of from_ca.pk
     *
     * @mbg.generated Thu Nov 24 17:41:58 CST 2022
     */
    public String getPk() {
        return pk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column from_ca.pk
     *
     * @param pk the value for from_ca.pk
     *
     * @mbg.generated Thu Nov 24 17:41:58 CST 2022
     */
    public void setPk(String pk) {
        this.pk = pk == null ? null : pk.trim();
    }
}